### PR TITLE
Scale testing

### PR DESCRIPTION
**Pull request by chrisstafford**

### CODE REVIEW

**Comment by joachimweyl** [comment]
@chrisstafford are you clear on how to resolve the checks?

**Comment by chrisstafford** [comment]
Merge conflicts are cleaned up, should be ready for merge after approval.

**Review by naved001 — APPROVED** [review]

**Comment by naved001** [comment]
we should probably use the squash and merge button for this.

**Comment by joachimweyl** [comment]
@chrisstafford is this ready for squash and merge?

**Pull request merged**
