### PR TITLE
Replace manual hardware list with generated inventory

### PR DESCRIPTION
**Pull request by larsks**
This replaces hardware.md with a CSV inventory generated by
the `rf-get-inventory.yaml` playbook in the nerc-ansible [1] repository.

[1]: https://github.com/ocp-on-nerc/nerc-ansible

### CODE REVIEW

**Comment by larsks** [comment]
@joachimweyl please see https://github.com/larsks/nerc-docs/blob/feature/generated-inventory/architecture/hardware.csv to see how this file displays when viewing it in your browser on github

**Comment by larsks** [comment]
[This](https://github.com/OCP-on-NERC/nerc-ansible/blob/main/playbooks/rf-get-inventory.yaml) is the playbook used to generate the CSV file.

**Comment by joachimweyl** [comment]
This looks amazing! Really awesome work @larsks. I do have some questions. I am not sure if these are questions for you or Nick/Justin. For now, I will start with you :)
1. Can we grab the Rack information from ansible?
1. Can we grab the Rack Bay information from ansible?
1. Can we grab the storage information from ansible?
1. Why is the Chassis Bay missing from the FC530's?
1. If our security settings that Justin is looking into allow us to show IP addresses can they also be pulled from Ansible?
1. How do we get the Test hosts (R640's) in this list?
1. Do we know why wrk-35 failed?

**Comment by larsks** [comment]
> Can we grab the Rack information from ansible?

We cannot: a server has no way to know in which rack it was installed.

> Can we grab the Rack Bay information from ansible?

If you mean "rack position", then again, no, for the same reason: a server doesn't know where you've put it.

> Can we grab the storage information from ansible?

Probably, yes. You mean like number of disks and disk size? I explicitly excluded this because in situations in which there are multiple disks and they aren't all identical, spreadsheet-style listing really isn't appropriate. If you think it's important we can add it; my general assumption is that all the disks are "big enough", and we're not going to be using local disk for user workloads in any case.

> Why is the Chassis Bay missing from the FC530's?

Because Dell doesn't appear to provide that information, at least not anyplace I've looked for it.

> If our security settings that Justin is looking into allow us to show IP addresses can they also be pulled frm Ansible?

We *can* add ip addresses, but I'm not sure that gets us anything: all the systems have hostnames that are are registered in DNS, and that's what we should use when referring to these systems.

> How do we get the Test hosts (R640's) in this list?

By adding the appropriate host names to [the inventory](https://github.com/OCP-on-NERC/nerc-ansible/tree/main/inventory/00-static). We can ask @jtriley for a list of hostnames that comprise the test cluster.

> Do we know why wrk-35 failed?

We do not, but it's not important now. We'll need to follow up with the NERC at some point.

**Review by joachimweyl — APPROVED** [review]
All of my questions were answered to my satisfaction. The only lingering question is where we will house the information of what Rack and Rack Location each Chassis is in.

**Comment by larsks** [comment]
> By adding the appropriate host names to [the inventory](https://github.com/OCP-on-NERC/nerc-ansible/tree/main/inventory/00-static). We can ask @jtriley for a list of hostnames that comprise the test cluster.

It looks as if these hosts may not support redfish (the API used to query the systems for hardware details), or may not have it enabled. I'm going to have to follow up with justin.

**Comment by larsks** [comment]
> The only lingering question is where we will house the information of what Rack and Rack Location each Chassis is in.

If we put that information into the ansible inventory, we could then use it when generating this report.

**Comment by mikthoma** [comment]
Reviewed the output and the above questions and answers. Agree with the answers and think the questions were thorough.

**Review by mikthoma — COMMENTED** [review]
Is it possible worker 35 is powered off or down?

**Review by mikthoma — COMMENTED** [review]
With the discussed questions and answers feel this is in good position to move forward.

**Comment by larsks** [comment]
> Is it possible worker 35 is powered off or down?

@mikthoma even if the system was powered off, we would expect to still have idrac access.

**Pull request merged**
