### PR TITLE
Add bios version to hardware inventory

### PR DESCRIPTION
**Pull request by larsks**

### CODE REVIEW

**Comment by joachimweyl** [comment]
@larsks do we have any idea why wrk0-9 failed?

**Review by mikthoma — APPROVED** [review]
Adding in BIOS information.

**Comment by larsks** [comment]
@joachimweyl the nodes in the test cluster failed because need a firmware update. Right now they're in use by the NERC folks so we can't apply updates (which require a reboot). These are just the test cluster machines and aren't at all time critical; we'll address this at some point but not anytime soon.

**Comment by larsks** [comment]
@mikthoma This includes both the bios version and the management firmware version.

**Pull request merged**
