### PR TITLE
Updated Hardware Headings

### PR DESCRIPTION
**Pull request by joachimweyl**
updated hardware.md with new headings
added new column
corrected column headings

### CODE REVIEW

**Comment by larsks** [comment]
@joachimweyl this still has the problem that there are only three controllers in the infra cluster, not 12. And similarly for the production cluster -- there will only be three controllers there as well.

**Comment by joachimweyl** [comment]
@larsks there are 3x SD530 chassis in infra, each one has 4 blades which means there are 12 blades. I must be using the wrong terminology.
1. SD530 = Chassis as well as a Controler?
1. Blade = Node?

**Comment by joachimweyl** [comment]
Working with @mikthoma to gather the data for the clusters and adding serial numbers, mac addresses, and bay location

**Comment by larsks** [comment]
Please see https://github.com/OCP-on-NERC/docs/pull/15 for an alternative take on this.

**Comment by larsks** [comment]
We've merged #15 so I am closing this pr.

**Pull request closed without merging**
