### PR TITLE
Firmware automation

### PR DESCRIPTION
**Pull request by chrisstafford**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202563838847747
  - https://app.asana.com/0/0/1202563838847749

### CODE REVIEW

**Comment by chrisstafford** [comment]
My linter isn't picking up any more trailing white spaces.
image

**Comment by joachimweyl** [comment]
@chrisstafford it might be worth confirming you have no lines (not inside comment blocks) longer than 79 char?

**Comment by larsks** [comment]
@chrisstafford it's better just to run the same linters that we're using here: the `README` has instructions for how to configure them. I'll fix up this PR.

**Comment by larsks** [comment]
I have fixed the linting errors, squashed all the fixup commits into their parents, and removed some unnecessary commits from the PR.

**Review by larsks — APPROVED** [review]
These docs look good!

**Pull request merged**
