### PR TITLE
Update hardware

### PR DESCRIPTION
**Pull request by chrisstafford**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202368393938906

### CODE REVIEW

**Review by joachimweyl — APPROVED** [review]
Thank you for updating the data on the FX2's. Next step is gathering the data on the R640's.

**Review by larsks — APPROVED** [review]
Look great, thank you!

**Comment by larsks** [comment]
It looks like this branch needs a rebase. Once that's done we can merge it.

**Comment by joachimweyl** [comment]
@larsks @chrisstafford  is out on active duty until 20th should we merge this as is or copy his changes and just create a new PR? @mikthoma this is referring to [this](https://app.asana.com/0/0/1202368393938906/f) Asana task that I have reassigned to you. We still need to track down the R640's last pieces of information. And the Networking hardware update I passed to Chris but I don't see that it made it in so here it is.
R1-PA-C08 (1-A-8) is a pair of Nexus 9336 going in next week
R7-PC-C03 (7-C-3) is a single cisco Nexus9000 C93180YC-FX for data and a Dell N3048 for mgmt
R7-PB-C19 (7-B-19) and P2-PB-C14 (2-B-14) are dual cisco Nexus9000 C93180YC-EX in a vPC and a Dell N3048

**Comment by larsks** [comment]
Rebased and removed typo-fix commits.

**Pull request merged**
